services:

  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "81:80"
    volumes:
      - ./images/php/app/public:/var/www/html/app/public

  php:
    build: images/php
    volumes:
      - ./images/php:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
    ports:
      - "9000:9000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: lumen
      POSTGRES_DB: lumen
      POSTGRES_USER: lumen

  adminer:
    image: adminer
    restart: always
    ports:
      - 33:8080