version: "3.8"

services:

  app:
    container_name: app_container
    build:
      context: ../project/
      dockerfile: ../deploy/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ../project/:/var/www

  nginx:
    container_name: nginx_container
    build: nginx
    ports:
      - "81:80"
    volumes:
      - ../project/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../project/public:/var/www/public

  db:
    image: postgres
    container_name: db_container
    tty: true
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "lumen"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"


  adminer:
    image: adminer
    restart: always
    ports:
      - 63:8080


